[package]
name = "lamport_sigs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
digest = "0.10"

[dev-dependencies]
sha2 = "0.10"

